name: Feature Request
description: Request a new feature or enhancement for the school activities website
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a new feature! Please fill out the information below to help us understand what you need.

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: What problem are you trying to solve? What is currently missing or difficult?
      placeholder: "Example: Students are having trouble finding activities that match their skill level."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: What would you like to see added or changed? Be as specific as possible.
      placeholder: "Example: Add a difficulty level filter (Beginner, Intermediate, Advanced) to help students find appropriate activities."
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know when this feature is complete? What should it do?
      placeholder: |
        Example:
        - Each activity can have an optional difficulty level
        - A new filter appears in the left sidebar
        - Students can filter activities by difficulty level
        - Activities without a difficulty level are shown in all filters
    validations:
      required: true

  - type: dropdown
    id: affected-area
    attributes:
      label: Which part of the website does this affect?
      options:
        - Activity listings/display
        - Filters and search
        - Student registration
        - Visual design/layout
        - Backend/database
        - Other
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information, examples, or screenshots that would help?
      placeholder: Add any other context, links, or screenshots about the feature request here.
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Really needed soon
    validations:
      required: true
